server:
  port: 8080
#    servlet:
#        context-path: /students

spring:
  datasource:
    url: jdbc:h2:mem:students
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console-students
#     http://localhost:8080/h2-console-students
#security:
#


